//
//  SignupView.swift
//  Ripple
//
//  Created by Hasan Malik on 2026-02-25.
//


//
//  Welcome.swift
//  Ripple
//
//  Created by Hasan Malik on 2026-02-24.
//

import SwiftUI
internal import Auth
import Supabase

struct SignupView: View {
    
    @State private var name: String = ""
    @State private var email: String = ""
    @State private var password: String = ""
    
    @Binding var user: Profile?

    
    var body: some View {
        Text("Welcome to Ripple")
            .font(.largeTitle)
        TextField("name", text: $name)
            .padding()
            .background {
                RoundedRectangle(cornerRadius: 10)
                    .stroke(.primary, lineWidth: 1)
            }
            .padding()
        TextField("email", text: $email)
            .padding()
            .background {
                RoundedRectangle(cornerRadius: 10)
                    .stroke(.primary, lineWidth: 1)
            }
            .padding()
        SecureField("password", text: $password)
            .padding()
            .background {
                RoundedRectangle(cornerRadius: 10)
                    .stroke(.primary, lineWidth: 1)
            }
            .padding()
        
        Button("Sign Up") {
            Task { // task is like async in react!
                do {
                    try await supabase.auth.signUp(email: email, password: password)
                    // the above line will create a row in the auth.users table, containing an id (generated by default, email, and password)
                    // then, thanks to our trigger+function in PostgreSQL, a row with the id and email will be made in the public.profiles table
                    // now, send the name to the public.profiles table:
                    let currentID = try await supabase.auth.session.user.id
                    try await supabase.from("profiles").update(["name": name]).eq("id", value: currentID).execute()
                    // btw, in case you didn't know, ["name": name] is a dict in Swift
                    
                    await MainActor.run {
                        print("About to set user: \(name), \(email)")
                        user = Profile(currentID, name, email)
                        print("user: \(user?.name) \(user?.email)")
                    }

                    
                } catch {
                    print("Error occured in sign up: \(error)")
                }
            }
        }
        .padding()
        .background {
            RoundedRectangle(cornerRadius: 10)
                .stroke(.primary, lineWidth: 1)
        }
//        NavigationLink(destination: LoginView(user: $user)){
//            Text("Already have an account? Log in")
//                .font(.body)
//                .padding()
//                .foregroundStyle(.secondary)
//        }
    }
    

}

#Preview {
    @Previewable @State var user: Profile? = nil
    NavigationStack{
        SignupView(user: $user)
    }
}

